### ISSUE TITLE
Waiting for longer jobs

### ISSUE THREAD

**Issue by mfikes** [cljs-oss/canary#1]
I found with Coal Mine, that the maximum allowed time for a job is around 45 minutes. This only applies to the granularity of a job, not the entire build, which has no time limit. So, for example, with Coal Mine, I addressed this by splitting the monolithic test job into smaller pieces, each of which run within a small amount of time, while the entire build could take longer than 45 minutes. See https://github.com/mfikes/coal-mine/blob/bda124095951dba9ce1ea673cd84d57837596ed5/.travis.yml#L16-L28 

With the change above, Coal Mine actually completes within 20 minutes (likely because the more fine-grained breakdown of jobs resulted in less memory pressure on the JVM during the build phase). But, I'm still adding tests to Coal Mine and I wouldn't be surprised if the total build time ends up exceeding 45 minutes.

So, I'm worried about Canary in that it may be using a job to wait for a task to complete. This is a bit of speculation on my part, but when Coal Mine took 45 minutes and was finally terminated, it appeared to cause Canary to also fail in the same way:

```
* Still waiting for 1 remaining task...
* Still waiting for 1 remaining task...
* Still waiting for 1 remaining task...
* Still waiting for 1 remaining task...
* Still waiting for 1 remaining task...
* Still waiting for 1 remaining task...
The job exceeded the maximum time limit for jobs, and has been terminated.
```

A band-aid would perhaps be to make sure that "waiting" jobs themselves terminate within, say 30 minutes, but to queue up enough of them to ensure that all tasks complete (so, with that approach, there might be a balance of "waiting" jobs that simply terminate early since all of the tasks are complete).

Another approach might be to make things asynchronous somehow.

I haven't put a lot of thought into either, but figured I'd log a ticket so that we can start pondering how to deal with this situation.

**Comment by darwin** [comment]
Congratulations for the Coal Mine project. It looks like a very useful addition for helping compiler developers to sleep well at night :)

I didn't know about the 45min limit on individual travis script invocations. Unfortunately Canary Travis job invokes [one monolithic script](https://github.com/cljs-oss/canary/blob/7797fc4a3dbddebcff918fa23ff34c360920f09a/.travis.yml#L33) which runs all the work inside a docker container. You are right that such 45min time limit applies here.

I think implementing some kind of pause/resume functionality for Canary Runner and then instructing Travis to invoke Canary Runner multiple times with pause/resume to stay under the time limit would fix the issue, but it would complicate implementation and require a bit of work.

Here is another proposal. What about making coal-mine travis script more flexible to accept configuration via an environmental variable? This way Canary could run multiple coal-mine tasks triggering multiple travis jobs each with specific value for partitioning the coal-mine work into smaller pieces.

You should be able to pass ENV variables into Travis build via `options` parameter of `travis/request-build!` call, specifically using `{:travis-config {:env {:global {"SOME_VAR_NAME" "SOME_VALUE"}}}}`. Look [here](https://github.com/cljs-oss/canary/blob/9c53e73282c49edc3949dd72b823deb716979f2b/runner/src/canary/projects/mfikes.clj#L14-L15) and consult Travis API docs.

The advantage of my proposal would be that coal-mine could run its pieces in parallel. I personally don't want to see Canary tasks to take too much time. That would make feedback loop of running Canary jobs less practical IMO. But it doesn't matter much for periodical nightly runs.

**Comment by mfikes** [comment]
@darwin Yeah, that sounds like a nice solution. If I'm understanding correctly would I simply make multiple entries here https://github.com/cljs-oss/canary/commit/9c53e73282c49edc3949dd72b823deb716979f2b, like `coal-mine-1` through `coal-mine-10`, recursively merging the my custom env options setup with the options passed into the job? I could easily do that, and this would simply result in _n_ smaller jobs (10 for now) that show up on the dashboard.

**Comment by darwin** [comment]
@mfikes Yes, exactly.

**Comment by darwin** [comment]
Not sure about that parallel run. Travis might queue builds of a single version of a repo triggered via API. Anyways, give it a shot. It should not be much work to try it.

**Comment by mfikes** [comment]
Resolved by partitioning the Coal Mine tests into individual Canary jobs, each of which takes considerably less time.
