### ISSUE TITLE
Provide ClojureScript GitHub Commit SHA

### ISSUE THREAD

**Issue by mfikes** [cljs-oss/canary#2]
In addition to `CANARY_CLOJURESCRIPT_VERSION`, provide `CANARY_CLOJURESCRIPT_COMMIT_SHA` (or somesuch) so that downstream projects can optionally make use of `deps.edn` overrides to pull ClojureScript directly from GitHub instead of fetching and running `install-canary.sh`

Note that the SHA needs to be the full SHA (not a prefix, otherwise `clojure` will reject it.)

**Comment by mfikes** [comment]
@darwin Let me know if you see any issue with this change.

**Comment by mfikes** [comment]
Here is an example of it working (adding `CANARY_CLOJURESCRIPT_REV` to the set of env vars):

```
$ export CANARY_BUILD=1
$ export CANARY_CLOJURESCRIPT_VERSION=1.9.1014-5daa572
$ export CANARY_CLOJURESCRIPT_REV=5daa57293dc97f7d1a6abafb5aa977365e286d61
$ export CANARY_CLOJURESCRIPT_JAR_URL=https://github.com/cljs-oss/canary/releases/download/r1.9.1014-5daa572/clojurescript-1.9.1014-5daa572.jar
$ export CANARY_TRAVIS_BUILD_URL=https://travis-ci.org/cljs-oss/canary/builds/333909385
```

**Comment by darwin** [comment]
looks good to me
