### ISSUE TITLE
add support for CANARY_CLOJURESCRIPT_REPO

### ISSUE THREAD

**Issue by darwin** [cljs-oss/canary#5]
Triggering a job on a foreign repo breaks in projects which install compiler via deps.edn.

For example job via efc6c5a643f74fa80b72b6e1b0e051f9fbe4b464 breaks in https://travis-ci.org/cljsrn/side-fx/builds/400548312#L464

After exposing CANARY_CLOJURESCRIPT_REPO similar to CANARY_CLOJURESCRIPT_REV, it should be an easy fix.

**Comment by darwin** [comment]
AFAICT affected projects are side-fx and coal-mine. 

@mfikes Will leave it for you to eventually fix them. It has a super low priority.

**Comment by mfikes** [comment]
coal-mine: https://github.com/mfikes/coal-mine/commit/ee69b7170f0fa06e7d771b76555b696b53ec10ab
side-fx: https://github.com/cljsrn/side-fx/commit/a7814d41d4e05d46d6548847005047a7c7a21d43
