### ISSUE TITLE
Can't Install Oracle Java 8 PPA

### ISSUE THREAD

**Issue by mfikes** [cljs-oss/canary#6]
See

https://travis-ci.org/cljs-oss/canary/builds/525243029#L1032

**Comment by darwin** [comment]
We can probably switch to Java 11.

I did this in my other repo with travis CI tests in docker:
https://github.com/binaryage/dirac/commit/0547a443ef0521ff09befa63b38b15f795da5af7

I will look into it tomorrow and review the whole container with updated software.
